### ISSUE TITLE
Kickass 1.9 not working

### ISSUE THREAD

**Issue by JerjerBinks** [MaurizioRicci/qBittorrent_search_engines#4]
Hi,

Maybe again a domain change of KickAss because not working here.
The search works, but when I try to download I have an error. I attached a sreenshot.
I'm using v1.9 in Qb v4.1.5.
Thanks for your work !

![image](https://user-images.githubusercontent.com/20711914/52913436-7f27ca80-32be-11e9-88e7-391952bdefde.png)

**Comment by MaurizioRicci** [comment]
Hi, it's because KickAss, like most torrent sites now use a third part site to deliver links. They want you to open various page and see ads before giving you the link. Sad story but there is no workaround (in the first page of the service used named myLink you can clearly see google's captcha form). The only way is in qbt to click on the show page button and download manually from myLink.

**Comment by bitingsock** [comment]
If I'm looking at this right, the url is just in the form https://mylink.me.uk/?url=magnet:?xt.....
Seems like you can just take that first bit off and you have a magnet link.

**Comment by MaurizioRicci** [comment]
@bitingsock 
It's not that simple, i have extracted a magnet link but it doesn't appear to be a valida magnet url.
Tried with
magnet%25xt%253Durn%253Abtih%253Aa3888d1acc2e25a41c76d7a5befb4234b1f62640%2526dn%253DLegendary.Tomb.of.the.Dragon.2013.1080p.BluRay.H264.AAC%2526tr%253Dudp%25253A%25252F%25252Ftracker.leechers-paradise.org%25253A6969%2526tr%253Dudp%25253A%25252F%25252Ftracker.openbittorrent.com%25253A80%2526tr%253Dudp%25253A%25252F%25252Fopen.demonii.com%25253A1337%2526tr%253Dudp%25253A%25252F%25252Ftracker.coppersurfer.tk%25253A6969%2526tr%253Dudp%25253A%25252F%25252Fexodus.desync.com%25253A6969&rlz=1C1CHBD_itIT840IT840&oq=magnet%25xt%253Durn%253Abtih%253Aa3888d1acc2e25a41c76d7a5befb4234b1f62640%2526dn%253DLegendary.Tomb.of.the.Dragon.2013.1080p.BluRay.H264.AAC%2526tr%253Dudp%25253A%25252F%25252Ftracker.leechers-paradise.org%25253A6969%2526tr%253Dudp%25253A%25252F%25252Ftracker.openbittorrent.com%25253A80%2526tr%253Dudp%25253A%25252F%25252Fopen.demonii.com%25253A1337%2526tr%253Dudp%25253A%25252F%25252Ftracker.coppersurfer.tk%25253A6969%2526tr%253Dudp%25253A%25252F%25252Fexodus.desync.com%25253A6969&aqs=chrome..69i57.7838j0j9&sourceid=chrome&ie=UTF-8

**Comment by bitingsock** [comment]
You just need to decode the url. https://www.urldecoder.org/ for example decodes this into a proper urn. I don't know if qbit includes a url decoder otherwise you'd need to write one in python. But given to low range of encoded characters a string replace may suffice.

**Comment by MaurizioRicci** [comment]
> You just need to decode the url. https://www.urldecoder.org/ for example decodes this into a proper urn. I don't know if qbit includes a url decoder otherwise you'd need to write one in python. But given the low range of encoded characters a string replace may suffice.

Perfect not i works as expected
