### ISSUE TITLE
Foxcili Search Engine Broken

### ISSUE THREAD

**Issue by closewall** [MaurizioRicci/qBittorrent_search_engines#6]
It was working for me like a month ago, but I tried it today, and after returning results for one search (which was already slower than usual), it just decided to stop. All new searches end with an error symbol on the tab after approximately 1 second.

![g89](https://user-images.githubusercontent.com/49519142/55950788-12ff8c80-5c99-11e9-802b-ab1b47a19257.jpg)

**Comment by Superseba97** [comment]
Hey I tried using horriblesubs.py search engine (written by maurizio) and it is giving me this kind of error, I don't know if it's correlated with yours, but it seems different.
![image](https://user-images.githubusercontent.com/48996500/55974981-3a4e5d80-5c89-11e9-885b-600fcbbe949d.png)
("Sconosciuto" means "Unknown", and it won't let me find the download even if it shows that it exists)

**Comment by MaurizioRicci** [comment]
@closewall it appears that 'http://foxcili.org/' no longer exist but i don't know the new domain.

**Comment by MaurizioRicci** [comment]
@closewall it appears that 'http://foxcili.org/' now has got Google anti robot filter before entering the site. Thus i imagine the only way to browse that site is by hand.
