### ISSUE TITLE
Horriblesubs.py

### ISSUE THREAD

**Issue by Superseba97** [MaurizioRicci/qBittorrent_search_engines#7]
Hello, I tried using horriblesubs.py search engine (first time using "unofficial" search engine in qbittorrent), I have encountered this error
![image](https://user-images.githubusercontent.com/48996500/55974981-3a4e5d80-5c89-11e9-885b-600fcbbe949d.png)
("Sconosciuto" means "Unknown", and it won't let me find the download even if it shows that those torrents exist, my other search engines work though)

**Comment by MaurizioRicci** [comment]
@Superseba97 this is not an issue. If you run a search on Horriblesubs you will get a simple page with only the filenames (no seed, no leech, no filesize), that's what the search plugin returns to you. I tested today and it still works.
![Cattura](https://user-images.githubusercontent.com/33112636/56596234-7a4e0280-65f0-11e9-8596-34d5aa47316d.PNG)
